<h1 style="color:RED"> Introduction to NumPy </h1>

<ul>
   <li>NumPy is Numerical Python.</li>
   <li>It is generally use for working with array.</li>
   <li>NumPy is a python library created in 2005 that perform numerical calculations.</li>
</ul>

<h1 style="color:RED">Use of NumPy</h1>

<ul>
    <li>Data Sciensce</li>
    <li>Machine Learning</li>
    <li>Image and Signal processing</li>
    <li>Scintific Computing</li>
</ul>

<h1 style="color:Red">Creating NumPy array</h1>

**import NumPy**

In [159]:
import numpy as np

<h1 style="color:RED;">Creating ndarray Using List and Tuple</h1>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Example</th>
  </tr>
  <tr>
    <td>0-D</td>
    <td>scalar - A single element</td>
  </tr>
  <tr>
    <td>1-D</td>
    <td>Vector - A list of integers</td>
  </tr>
  <tr>
      <td>2-D</td>
      <td>Matrix - A spreedsheet of data</td>
  </tr>
  <tr>
      <td>3-D</td>
      <td>Tensor - Storing a color image </td>
  </tr>
</table>


**0-dimenstional array (Scalar)**

In [160]:
a=np.array(9) 
a

array(9)

**1-dimenstiional array (Vector)**

In [161]:
a1=np.array((10,20,30,40,50,60,70,80,90,100))     
a1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [162]:
b1=np.array([5,15,25,35,45,55,65,75,85,95])
b1

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

##### indexing - access the single element.

In [163]:
a1[5]

np.int64(60)

##### Slicing - access the list.

In [164]:
a1[1:6]

array([20, 30, 40, 50, 60])

##### Attributes

<table border="1">
  <tr>
    <th>Attribute</th>
    <th>Use</th>
  </tr>
  <tr>
    <td>shape()</td>
    <td><li>Return the tuple representing the shape.</li>
        <li>1-D : return number of element.</li>
        <li>2-D : return number of row and column.</li>
        <li>3-D : return number of matrix ,row and column</li>
    </td>
  </tr>
  <tr>
    <td>ndim()</td>
    <td><li>Return the number of dimention.</li></td>
  </tr>
  <tr>
      <td>size()</td>
      <td><li>Return total number of elements.</li></td>
  </tr>
  <tr>
      <td>dtype()</td>
      <td><li>Return the data type</li> </td>
  </tr>
  <tr>
      <td>itemsize()</td>
      <td><li>Return size in bytes</li> </td>
  </tr>
</table>

In [165]:
a1.shape  

(10,)

In [166]:
a1.ndim

1

In [167]:
a1.size

10

In [168]:
a1.dtype

dtype('int64')

In [169]:
a1.itemsize

8

##### Reshape - Change the dimention

In [170]:
# 1-dimentional to 2-dimentional
a1.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [171]:
# 1-dimentional to 3-dimentional
a1.reshape(5,1,2)

array([[[ 10,  20]],

       [[ 30,  40]],

       [[ 50,  60]],

       [[ 70,  80]],

       [[ 90, 100]]])

In [172]:
# Convert the 1-dimentional
a1.reshape(-1)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

**2-dimentional  (Matrix)**

In [173]:
a2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])       
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [174]:
b2=np.array([[7,8,9,10,11,34],[13,14,15,16,34,17]]) 
b2

array([[ 7,  8,  9, 10, 11, 34],
       [13, 14, 15, 16, 34, 17]])

##### Indexing

In [175]:
a2[1,3]

np.int64(10)

##### Slicing

In [176]:
a2[1:3,1:3]

array([[ 8,  9],
       [14, 15]])

##### Attributes

In [177]:
a2.shape

(3, 6)

In [178]:
a2.ndim

2

In [179]:
a2.size

18

In [180]:
a2.dtype

dtype('int64')

In [181]:
a2.itemsize

8

##### Reshape

In [182]:
# 2-dimentional to 3-dimentional
a2.reshape(2,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [183]:
# 2-dimentional to 1-dimentional
a2.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

**3-dimentional (Tensor)**

In [184]:
a3=np.array([[[2,3,2,4,5],[3,5,7,3,2],[3,5,3,2,4]],[[2,4,5,1,3],[4,2,4,6,3],[3,9,6,4,2]]])       
a3

array([[[2, 3, 2, 4, 5],
        [3, 5, 7, 3, 2],
        [3, 5, 3, 2, 4]],

       [[2, 4, 5, 1, 3],
        [4, 2, 4, 6, 3],
        [3, 9, 6, 4, 2]]])

In [185]:
b3=np.array([[[21,23,34,32,43],[34,43,23,23,34],[43,56,43,32,43]],[[43,45,67,54,34],[34,67,43,12,67],[43,45,65,76,54]]])
b3

array([[[21, 23, 34, 32, 43],
        [34, 43, 23, 23, 34],
        [43, 56, 43, 32, 43]],

       [[43, 45, 67, 54, 34],
        [34, 67, 43, 12, 67],
        [43, 45, 65, 76, 54]]])

##### indexing

In [186]:
a3[1,1,2]

np.int64(4)

##### Slicing

In [187]:
a3[0,0:3,2:4]

array([[2, 4],
       [7, 3],
       [3, 2]])

##### Attributes

In [188]:
a3.shape

(2, 3, 5)

In [189]:
a3.ndim

3

In [190]:
a3.size

30

In [191]:
a3.dtype

dtype('int64')

In [192]:
a3.itemsize 

8

##### Reshape

In [193]:
# 3-dimentional to 2-dimentional
a3.reshape(10,3)

array([[2, 3, 2],
       [4, 5, 3],
       [5, 7, 3],
       [2, 3, 5],
       [3, 2, 4],
       [2, 4, 5],
       [1, 3, 4],
       [2, 4, 6],
       [3, 3, 9],
       [6, 4, 2]])

In [194]:
# 3-dimentional to 1-dimentional
a3.reshape(-1)

array([2, 3, 2, 4, 5, 3, 5, 7, 3, 2, 3, 5, 3, 2, 4, 2, 4, 5, 1, 3, 4, 2,
       4, 6, 3, 3, 9, 6, 4, 2])

<h1 style="color:Red">Type Casting</h1>

In [195]:
a=a.astype(complex)
a

array(9.+0.j)

In [196]:
a1=a1.astype(float)
a1

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [197]:
a2=a2.astype(float)
a2

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.]])

In [198]:
a3=a3.astype(float)
a3

array([[[2., 3., 2., 4., 5.],
        [3., 5., 7., 3., 2.],
        [3., 5., 3., 2., 4.]],

       [[2., 4., 5., 1., 3.],
        [4., 2., 4., 6., 3.],
        [3., 9., 6., 4., 2.]]])

<h1 style="color:red">Create array of fixed size</h1>

### Creating ndarray of ones

In [199]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [200]:
np.ones((6,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Creating ndarray of zeros

In [201]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [202]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Creating ndarray for specific value

In [203]:
np.full((4,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [204]:
np.full((3,6),1.3)

array([[1.3, 1.3, 1.3, 1.3, 1.3, 1.3],
       [1.3, 1.3, 1.3, 1.3, 1.3, 1.3],
       [1.3, 1.3, 1.3, 1.3, 1.3, 1.3]])

### Create identity Matrix

In [205]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Diagonal Matrix

In [206]:
d=np.diag((2,4,5))
d

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [207]:
di=np.diag([4,6,8])
di

array([[4, 0, 0],
       [0, 6, 0],
       [0, 0, 8]])

### Create array with random value

In [214]:
r=np.random.rand(3,4)       # 3,4 array of random floats in [0, 1)

r

array([[0.006781  , 0.15886213, 0.27049387, 0.27166167],
       [0.34465179, 0.13874379, 0.79319194, 0.48160397],
       [0.33858952, 0.44540874, 0.87068767, 0.41078051]])

In [229]:
r1=np.random.randint(2,10,size=(3,4))    # 3x4 array of ints from 2 to 9
r1

array([[6, 9, 3, 7],
       [7, 3, 7, 3],
       [5, 5, 4, 9]], dtype=int32)

In [230]:
r2=np.random.randn(3,4)
r2

array([[-1.23442386, -0.47448114, -0.33885222,  0.23096603],
       [ 1.63348665,  0.30412171,  0.52922541,  1.82669911],
       [ 0.52896099, -0.1998483 , -0.16140533, -0.45566705]])

### Create array of Arange() Function

In [239]:
a1=np.arange(11)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [240]:
a1=np.arange(5,51,5)
a1

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

**Reshape and Arange**

In [241]:
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Create using linspace() Function

In [244]:
a=np.linspace(0,5,10)
a

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [245]:
b=np.linspace(2,20,15)
b

array([ 2.        ,  3.28571429,  4.57142857,  5.85714286,  7.14285714,
        8.42857143,  9.71428571, 11.        , 12.28571429, 13.57142857,
       14.85714286, 16.14285714, 17.42857143, 18.71428571, 20.        ])

<h1 style="color:Red"> Joinning Array</h1>

In [246]:
# Create array
j1=np.array((10,20,30,40,50,60))
j1

array([10, 20, 30, 40, 50, 60])

In [247]:
j2=np.array((1,2,3,4,5,6))
j2

array([1, 2, 3, 4, 5, 6])

In [248]:
j3=j1.reshape(3,2)
j3

array([[10, 20],
       [30, 40],
       [50, 60]])

In [249]:
j4=j2.reshape(3,2)
j4

array([[1, 2],
       [3, 4],
       [5, 6]])

**Using concatenate() function**

In [250]:
np.concatenate((j1,j2))  # joinning 1-d array 

array([10, 20, 30, 40, 50, 60,  1,  2,  3,  4,  5,  6])

In [251]:
np.concatenate((j3,j4))       # joinning 2-d array  
                               # syntax for - concatenate((aaray1,array2),axis)
                               # axis-0 = column wise joinning (Defalut axis-0)
                               # axis-1 = row wise joinning

array([[10, 20],
       [30, 40],
       [50, 60],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6]])

In [252]:
np.concatenate((j4,j3),axis=1)

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40],
       [ 5,  6, 50, 60]])

**Using hstack() function** - Row wise join

In [253]:
np.hstack((j1,j2))

array([10, 20, 30, 40, 50, 60,  1,  2,  3,  4,  5,  6])

In [254]:
np.hstack((j3,j4))           # join for row wise

array([[10, 20,  1,  2],
       [30, 40,  3,  4],
       [50, 60,  5,  6]])

In [255]:
np.hstack((j4,j3))

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40],
       [ 5,  6, 50, 60]])

**Using vstack() function** - Column wise join

In [256]:
np.vstack((j1,j2))                      # join for column wise

array([[10, 20, 30, 40, 50, 60],
       [ 1,  2,  3,  4,  5,  6]])

In [257]:
np.vstack((j3,j4))

array([[10, 20],
       [30, 40],
       [50, 60],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6]])

In [258]:
np.vstack((j4,j3))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40],
       [50, 60]])

<h1 style="color:red">Spliting Array </h1>

In [259]:
s=np.array(( 7, 45,  7,  4,  0, 21, 21, 39, 35, 35))
s

array([ 7, 45,  7,  4,  0, 21, 21, 39, 35, 35])

In [260]:
np.array_split(s,5)

[array([ 7, 45]),
 array([7, 4]),
 array([ 0, 21]),
 array([21, 39]),
 array([35, 35])]

In [261]:
np.array_split(s,10)

[array([7]),
 array([45]),
 array([7]),
 array([4]),
 array([0]),
 array([21]),
 array([21]),
 array([39]),
 array([35]),
 array([35])]

In [262]:
np.array_split(s,7)

[array([ 7, 45]),
 array([7, 4]),
 array([ 0, 21]),
 array([21]),
 array([39]),
 array([35]),
 array([35])]

In [263]:
np.array_split(s,15)

[array([7]),
 array([45]),
 array([7]),
 array([4]),
 array([0]),
 array([21]),
 array([21]),
 array([39]),
 array([35]),
 array([35]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64)]

<h1 style="color:red">Searching array</h1>

In [268]:
r=np.random.randint(1,50,10)
r

array([43, 11, 45,  1, 48, 40,  3, 15, 38, 21], dtype=int32)

In [269]:
np.where(r==13)   # output - index number

(array([], dtype=int64),)

In [270]:
np.where(r==11)

(array([1]),)

In [271]:
r1=np.random.randint(1,50,size=(3,4))
r1

array([[14, 43, 17, 41],
       [41, 28, 20, 10],
       [45, 30,  6,  2]], dtype=int32)

In [272]:
np.where(r1==6)

(array([2]), array([2]))

In [273]:
np.where(r1==27)

(array([], dtype=int64), array([], dtype=int64))

<h1 style="color:red">Sorting Array</h1>

In [274]:
t=np.random.randint(1,100,15)
t

array([82, 73, 33, 77, 65, 13, 11, 25, 15, 26, 13, 67, 79, 65, 53],
      dtype=int32)

In [275]:
np.sort(t)            # default acsending sorting

array([11, 13, 13, 15, 25, 26, 33, 53, 65, 65, 67, 73, 77, 79, 82],
      dtype=int32)

In [276]:
np.sort(t)[::-1]    # decending sorting

array([82, 79, 77, 73, 67, 65, 65, 53, 33, 26, 25, 15, 13, 13, 11],
      dtype=int32)

In [277]:
t1=np.random.randint(1,50,size=(5,3))
t1

array([[ 4,  5, 19],
       [22, 27, 21],
       [33,  4, 36],
       [ 3, 25, 13],
       [ 3, 33, 19]], dtype=int32)

In [278]:
np.sort(t1)

array([[ 4,  5, 19],
       [21, 22, 27],
       [ 4, 33, 36],
       [ 3, 13, 25],
       [ 3, 19, 33]], dtype=int32)

<h1 style="color:red">Copy & View</h1>

In [279]:
import numpy as np

In [280]:
c=np.array((20,40,60,80,100,100))
c1=c.copy()
c1[5]=120
print("Original array: ",c)
print("Copy array: ",c1)

Original array:  [ 20  40  60  80 100 100]
Copy array:  [ 20  40  60  80 100 120]


In [281]:
v=np.array((10,30,50,70,90,100))
v1=v.view()
v1[5]=110
print("Original array: ",v)
print("View array: ",v1)

Original array:  [ 10  30  50  70  90 110]
View array:  [ 10  30  50  70  90 110]


<h1 style="color:red">Opeartors</h1>

### Arithmetic Operation

##### 1-D Array

In [ ]:
a1=np.array([10,23,34,54,45])
a1

In [ ]:
a2=np.array((34,56,67,78,54))
a2

**Addition**

In [ ]:
a1+a2

In [ ]:
np.add(a1,a2)

In [ ]:
a1+2

**Substraction**

In [ ]:
a1-a2

In [ ]:
a2-a1

In [ ]:
np.subtract(a2,a1)

In [ ]:
a1-5

**Multiplication**

In [ ]:
a1*a2

In [ ]:
np.multiply(a1,a2)

In [ ]:
a1*5

**Division**

In [ ]:
a1/a2

In [ ]:
a2/a1

In [ ]:
np.divide(a2,a1)

In [ ]:
a1/2

**Exploration**

In [ ]:
a1**2

In [ ]:
np.power(a1,2)

In [ ]:
a2**5

**Modulus (Return reminder)**

In [ ]:
a2%a1

In [ ]:
np.mod(a2,a1)

In [ ]:
a1%10

### Comparison Operation

In [ ]:
b1=np.array([10,20,30,40,50,80])
b1

In [ ]:
b2=np.array((20,30,35,40,60,70))
b2

**Less than (<)**

In [ ]:
b1<b2

In [ ]:
b2<b1

In [ ]:
np.less(b2,b1)

In [ ]:
b2<10

In [ ]:
10<b2

**Less than or equal to (<=)**

In [ ]:
b1<=b2

In [ ]:
b2<b1

In [ ]:
b2<=20

**Greater than (>)**

In [ ]:
b1>b2

In [ ]:
b2>b1

In [ ]:
b2>10

**Greater than or equal to (>=)**

In [ ]:
b1>=b2

In [ ]:
b2>=b1

In [ ]:
b1>=40

**Equal to (==)**

In [ ]:
b1==b2

In [ ]:
b1==50

In [ ]:
np.equal(b2,b1)

**not equal (!=)**

In [ ]:
b1!=b2

In [ ]:
b2!=20

In [ ]:
np.not_equal(b2,b1)

### Logical operator

In [ ]:
l1=np.array((True,False,False,False,True))
l1

In [ ]:
l2=np.array([True,True,True,True,True])
l2

**Logical and (logical_and)**

In [ ]:
np.logical_and(l1,l2)

**Logical or (logical_or)**

In [ ]:
np.logical_or(l1,l2)

**Logical not (logical_not)**

In [ ]:
np.logical_not(l2)

<h1 style="color:red">Statistical Function</h1>

In [282]:
s=np.array((10,30,50,70,90,20,40))
s

array([10, 30, 50, 70, 90, 20, 40])

In [283]:
np.mean(s)       # = (10+30+50+70+90,20,40)/7
                 # = 310/7
                 # = 44.28

np.float64(44.285714285714285)

In [284]:
np.median(s)

np.float64(40.0)

In [285]:
np.std(s)

np.float64(26.10809554642438)

In [286]:
np.percentile(s,2)

np.float64(11.2)

In [287]:
np.min(s)

np.int64(10)

In [288]:
np.max(s)

np.int64(90)

In [ ]:
import numpy as np
import time
list1=list(range(1,10000001))
list2=list(range(1,10000001))
start=time.time()
result=[list1[i]+list2[i] for i in range(len(list1))]
end=time.time()
list_time=end-start



array1=np.arange(1,10000001)
array2=np.arange(1,10000001)
start1=time.time()
result=array1+array2
end1=time.time()
array_time=end1-start1


if array_time<list_time:
    print("array is faster")
else:
    print("list is faster")


In [ ]:
import numpy as np
import time
array1=np.arange(1,10000001)
array2=np.arange(1,10000001)
start=time.time()
result=array1+array2
end=time.time()
time=end-start
print("array excution time is: ",time)